apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels: 
    name: redis-deploy
    app: demo-voting-app 
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: redis-pod
      app: demo-voting-app  
  template:
    metadata:
      name: redis-pod
      labels: 
        name: redis-pod
        app: demo-voting-app    #Application name for all components so we can group them but different components will have different name
    spec: 
      containers:
        - name: redis
          image: redis 
          ports:
            - containerPort: 6379  # port in which application listen 6379 default for redis)