apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels: 
    name: redis-pod
    app: demo-voting-app    #Application name for all components so we can group them but different components will have different name
spec: 
  containers:
    - name: redis
      image: redis 
      ports:
        - containerPort: 6379  # port in which application listen 6379 default for redis)