apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
    app: demo-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app 
  template:                   # copied from metadata and spec of pod.yaml
    metadata:
      name: result-app-pod
      labels: 
        name: result-app-pod
        app: demo-voting-app    #Application name for all components so we can group them but different components will have different name
    spec: 
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1 
          ports:
            - containerPort: 80  # port in which application listen